### GET all characters
http://localhost:3001/api/user

### POST a character
# @name AnUser
POST http://localhost:3001/api/user
Content-Type: application/json

{
    "name": "el",
    "surname": "maleante",
    "email": "elmaleante@gmail.com",
    "password": "OnePairOfPants123",
    "id": 1
    
}
### DELETE character
DELETE http://localhost:3001/api/user/:id


