### GET all categories
http://localhost:3000/api/category

### POST a new category
# @name AnUser
POST http://localhost:3000/api/category
Content-Type: application/json

{
    "name": "Ocio",
    "icon": "",
    "description": "",
    "userid": 1
}

### DELETE a category
# @name AnUser
DELETE http://localhost:3000/api/category/{id}
Content-Type: application/json

{
    "id": "1"
}