### GET all categories
http://localhost:3001/api/category

### POST a new category
# @name AnUser
POST http://localhost:3001/api/category
Content-Type: application/json

{
    "name": "Ocio",
    "icon": "",
    "description": "",
    "userid": 1
}

### GET one category
# @name AnUser
@id = 1
GET http://localhost:3001/api/category/{{id}}
Content-Type: application/json

# {
#     "id": 1
# }

### DELETE a category
# @name AnUser
@id = 1
DELETE http://localhost:3001/api/category/{{id}}
Content-Type: application/json

# {
#     "id": "1"
# }